<?php
// FILE: debug_view_trip.php
// PURPOSE: To safely execute view_trip.php with full error reporting and step-by-step logging.

// --- 1. SETUP DEBUG ENVIRONMENT ---

// Force PHP to display all errors, including fatal ones that cause a white screen.
error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('log_errors', 1); // Also log errors to a file, just in case.

// Start output buffering to capture everything.
ob_start();

/**
 * A simple logging function to print messages to the screen during execution.
 * This helps us trace the script's path and see where it stops.
 * @param string $message The message to log.
 * @param array|null $data Optional data to display.
 */
function log_debug($message, $data = null) {
    echo '<div style="font-family: monospace; border-left: 4px solid #3498db; padding: 8px 12px; margin: 8px; background-color: #f0f8ff;">';
    echo '<strong>[' . date('Y-m-d H:i:s') . '] DEBUG:</strong> ' . htmlspecialchars($message);
    if ($data !== null) {
        echo '<pre style="background-color: #e3f2fd; padding: 10px; border-radius: 4px; margin-top: 5px; white-space: pre-wrap; word-wrap: break-word;">';
        print_r($data);
        echo '</pre>';
    }
    echo '</div>';
    flush(); // Immediately send the output to the browser.
}

// --- 2. EXECUTION & LOGGING ---

log_debug('Debugger initialized. Starting execution...');

try {
    // Check if the main script file exists before trying to include it.
    if (!file_exists(__DIR__ . '/view_trip.php')) {
        throw new Exception('The file "view_trip.php" was not found in the same directory. Please ensure the debugger file is in the correct location.');
    }

    log_debug('Attempting to include "view_trip.php"...');
    
    // This is where we run your original script.
    // Any error inside this file will be caught and displayed.
    require_once __DIR__ . '/view_trip.php';

    log_debug('"view_trip.php" included successfully. Script finished.');

} catch (Throwable $e) {
    // Catch any fatal error or exception that would normally cause a white screen.
    log_debug('A critical error was caught!', [
        'error_type' => get_class($e),
        'message' => $e->getMessage(),
        'file' => $e->getFile(),
        'line' => $e->getLine(),
        'trace' => $e->getTraceAsString()
    ]);
} finally {
    // --- 3. OUTPUT ---
    
    // Clean the buffer and get all the output generated by the script.
    $output = ob_get_clean();
    
    // If there was no output at all (besides our logs), it's a strong sign of a silent exit or redirect.
    if (trim(strip_tags($output)) === '') {
        log_debug('WARNING: The script produced no visible output. This could be due to an early `exit;`, `die;`, or a `Utils::redirect()` call. Review the logs above to see the last step before the script stopped.');
    }

    // Display the captured output from view_trip.php
    echo $output;
}

log_debug('Debugger finished.');

?>
